#!/usr/bin/env bash
# Regenerate gpu/metal/parity_golden.txt, the committed snapshot of Metal's own output that the parity sweep checks
# every scene against (see "Golden snapshot" in gpu/metal/metal_cpu_gpu_parity_check.cpp).
#
# Run it ONLY when a change to the rendered pictures is intended (a new feature, a deliberate accuracy fix), then
# review `git diff gpu/metal/parity_golden.txt` - every scene whose numbers moved should be a scene you meant to
# change. A drift you did not expect is a bug, not a reason to re-snapshot.
#
# Usage: scripts/update_metal_golden.sh [path/to/metal_cpu_gpu_parity_check]   (default: build_macos/...)
# It renders the 95-scene sweep with 3 different seeds (~3.5 min) and stores the per-scene mean of the seeds, so the
# snapshot carries less noise than any single run.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="${1:-$REPO_ROOT/build_macos/metal_cpu_gpu_parity_check}"
[[ -x "$BIN" ]] || { echo "ERROR: $BIN not found - build with -DRT_BUILD_METAL=ON first" >&2; exit 1; }
GOLDEN="$REPO_ROOT/gpu/metal/parity_golden.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

cd "$REPO_ROOT"   # the sweep resolves the pbrt scene files relative to the repo root (ctest runs it from here)
i=0
for seed in "" 777 4242; do
	i=$((i + 1))
	echo "[golden] pass $i/3 (seed ${seed:-default})..." >&2
	if [[ -n "$seed" ]]; then export METAL_PARITY_SEED="$seed"; else unset METAL_PARITY_SEED; fi
	METAL_PARITY_GOLDEN=off METAL_PARITY_DUMP="$TMP/dump_$i.txt" "$BIN" >/dev/null 2>&1 || true
	[[ -s "$TMP/dump_$i.txt" ]] || { echo "ERROR: pass $i produced no snapshot (no Metal device?)" >&2; exit 1; }
done

{
	echo "# Metal parity snapshot - generated by scripts/update_metal_golden.sh (mean of 3 seeds); do not edit by hand."
	echo "# id  R G B  then the 4x4 block means (row-major) of the Metal image."
	cat "$TMP"/dump_*.txt | awk '
		{ id=$1; n[id]++; for (k=2; k<=NF; k++) s[id,k]+=$k; nf[id]=NF; ids[id]=1 }
		END { for (id in ids) { printf "%s", id; for (k=2; k<=nf[id]; k++) printf " %.6f", s[id,k]/n[id]; printf "\n" } }' | sort
} > "$GOLDEN"
echo "[golden] wrote $(grep -vc '^#' "$GOLDEN") scenes to $GOLDEN" >&2
