#!/usr/bin/env bash
# Regenerates qt_gui/downloadable_assets.txt: the list of files the GUI's "Download missing files" button may fetch.
#
# Only files that are tracked in THIS repository's models/ folder are listed (the Stanford/test statue meshes), and they
# are fetched from this repository at the commit that last changed models/ - a fixed URL, so a later edit on main cannot
# change what a released app downloads. Each entry carries its size and SHA-256, which the downloader checks before it
# keeps a file. Third-party "whole environment" scenes (Sponza, Bistro, ...) are deliberately NOT listed: they are not
# hosted anywhere by this project.
#
# Run after adding or changing a file under models/ and commit the result (that commit must be pushed before a release,
# since the app downloads from the commit recorded here).
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
OUT="qt_gui/downloadable_assets.txt"
COMMIT="$(git log -1 --format=%H -- models)"
REMOTE="$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#; s#\.git$##')"
SLUG="${REMOTE#https://github.com/}"
{
	echo "# Generated by scripts/update_asset_manifest.sh - do not edit by hand."
	echo "# base <url prefix>, then one line per file: <path relative to the app folder> <bytes> <sha256>"
	echo "base https://raw.githubusercontent.com/$SLUG/$COMMIT/"
	git ls-files 'models/*.obj' | sort | while read -r f; do
		echo "$f $(wc -c < "$f" | tr -d ' ') $(shasum -a 256 "$f" | cut -d' ' -f1)"
	done
} > "$OUT"
echo "wrote $OUT ($(grep -vc '^#\|^base' "$OUT") files, commit ${COMMIT:0:10})"
