#pragma once
// asset_downloader.h - the GUI's "Download missing files" support.
//
// Scenes that need external mesh files show a warning naming what is missing (see
// SceneMetadataClient::missingAssets). For the files this project itself hosts - the statue meshes under
// models/ - this lets the user fetch them in one click instead of copying a folder around.
//
// What may be downloaded is a fixed list (:/assets/downloadable_assets.txt, generated by
// scripts/update_asset_manifest.sh): each entry has a path, a size and a SHA-256, and every file is fetched
// from one pinned commit of this repository, so what a released app downloads cannot change under it. A file
// is only kept if its size and hash match. Nothing outside the list is ever fetched, whatever a scene asks for.

#include <QFile>
#include <QList>
#include <QNetworkAccessManager>
#include <QObject>
#include <QString>

#include <memory>

class QNetworkReply;

namespace asset_downloader {

struct Entry {
	QString relativePath;   // "models/armadillo.obj", relative to the application folder
	qint64 size = 0;
	QString sha256;         // lower-case hex
};

struct Manifest {
	QString baseUrl;        // every entry's URL is baseUrl + relativePath
	QList<Entry> entries;

	// The entry for an absolute path under `appDir`, or nullptr when the file is not on the list.
	const Entry *find(const QString &appDir, const QString &absolutePath) const;
	QString urlFor(const Entry &e) const { return baseUrl + e.relativePath; }
};

// Parses the manifest text. Malformed lines are skipped; a missing "base" line yields an empty manifest.
Manifest parseManifest(const QString &text);

// The manifest compiled into the application. RT_ASSET_BASE_URL in the environment replaces its base URL
// (used by the self-test to download from a local server instead of GitHub).
const Manifest &builtInManifest();

struct Job {
	Entry entry;
	QString destination;    // absolute path the file is written to
};

// Downloads jobs one after another. Each file goes to "<destination>.part", is checked, then renamed into
// place - a cancelled or failed download never leaves a truncated model where the renderer would find it.
class Downloader : public QObject {
	Q_OBJECT
public:
	explicit Downloader(const Manifest &manifest, QObject *parent = nullptr);

	void start(const QList<Job> &jobs);
	void cancel();
	bool isRunning() const { return m_running; }

signals:
	// Overall bytes received so far / total expected, and the file currently being fetched.
	void progress(qint64 received, qint64 total, const QString &currentFile);
	// ok == true when every job finished and verified. On failure `error` says why (translated).
	void finished(bool ok, const QString &error, int filesDone);

private:
	void startNext();
	void finishWith(bool ok, const QString &error);
	void onReadyRead();
	void onReplyFinished();

	const Manifest &m_manifest;
	QNetworkAccessManager m_network;
	QList<Job> m_jobs;
	int m_index = 0;
	qint64 m_totalBytes = 0;
	qint64 m_doneBytes = 0;     // bytes of files already completed
	qint64 m_fileBytes = 0;     // bytes of the current file received so far
	bool m_running = false;
	bool m_cancelled = false;
	QNetworkReply *m_reply = nullptr;
	std::unique_ptr<QFile> m_file;
};

}  // namespace asset_downloader
