#pragma once
#include <QCoreApplication>
#include <QDebug>
#include <QHash>
#include <QSet>
#include <QString>
#include <QStringList>

// scene_technique_notes.h -- per-scene "what rendering technique does this
// demonstrate" text for the Settings tab's dynamic info icon (see
// MainWindow::updateSceneTechInfoIcon(), mainwindow_style.cpp).
//
// Unlike the ~27 other info-icon tooltips in this app (fixed text, written
// once at construction), this content is looked up fresh per selected
// scene. It lives here rather than as a new SceneDescriptor field/
// scene_metadata.dll export because it's pure GUI documentation, not
// renderer behavior - the same reasoning every other info-icon tooltip is
// GUI-only text, never round-tripped through the DLL.
//
// Scoped to self-contained scenes only (requires_files == false): every
// compiled-in procedural scene (src/TheRestOfYourLife/scenes*.h, including
// the Education entries and B24, all of which reuse another scene's
// geometry - see their own comments in scene_registry.h) plus every
// curated pbrt-example scene (bundled pbrt_scenes/*.pbrt files,
// registered via pbrt_scene_registry::build_curated_pbrt_scene_descriptor()
// in scene_registry.h, which hardcodes requires_files=false). A scene id
// with no entry here - every "Requires External Files" scene - falls back
// to an honest "not written yet" message in forScene() below, rather than
// silently showing nothing or stale content.
//
// This table has drifted out of sync with the registry more than once
// already (found via a user report, not warnIfOutOfSync() below - that
// guard only fires in debug builds, so a Release build silently ships the
// fallback text for a while before anyone notices). Whenever a new
// self-contained scene is added to scene_registry_data.h, add its note
// here in the SAME session, don't rely on spotting the fallback later.
namespace scene_technique_notes {

inline const QHash<QString, QString>& notes() {
	static const QHash<QString, QString> kNotes = {
		// ---------------------------------------------------------------
		// Basics (A1-A9, minus A4)
		// ---------------------------------------------------------------
		{"A1", QObject::tr(R"note(The Cornell box is one of the most famous test scenes in computer graphics: a small room with colored side walls, a glowing light panel set into the ceiling, a plain white box, and a glass sphere that both reflects and refracts the light around it. Watch how the red and green walls tint nearby white surfaces with bounced color, and how the ceiling light produces soft, clean shadows rather than a speckled, noisy look. Because it packs bounced light, a light source, and a glass object into one small room, this scene is usually the first place any lighting or material problem shows up.)note")},
		{"A2", QObject::tr(R"note(A tribute to the classic "Ray Tracing in One Weekend" finale: a checkerboard ground stretches to the horizon under a scattered field of small spheres in matte, metallic, and glass finishes. Look closely and some of the spheres appear slightly streaked - those are moving through the frame during the shot, captured with motion blur just like a camera would. Metal spheres range from mirror-sharp to soft and brushed depending on how rough their surface is. Three larger spheres out front - a clear glass ball, a plain matte sphere, and a perfect mirror - serve as a reference lineup for comparing the different finishes side by side.)note")},
		{"A3", QObject::tr(R"note(Two giant spheres, one sitting above the other, are wrapped in the same blue-and-white checkerboard pattern - not painted on, but generated mathematically so it wraps cleanly around the curved surface without stretching or seams. A few smaller spheres perched on top - one matte, one a softly blurred metal, one glass - give a sense of scale and show how the same light interacts differently with each material.)note")},
		{"A5", QObject::tr(R"note(The ground and a large sphere are covered in a procedural marble-like pattern - swirling, naturally varied bands of color generated by a mathematical noise function (Perlin noise) rather than a painted image, the same kind of technique used to make believable clouds, wood grain, or marble in computer graphics and games. Two smaller spheres nearby use a finer, busier version of the same pattern for contrast, lit by a glowing light panel overhead that gives the whole scene soft, realistic shadows.)note")},
		{"A6", QObject::tr(R"note(Five flat colored panels are arranged at different angles - facing forward, sideways, and up - to check that each one catches light correctly no matter which way it's turned. A separate glowing panel floating in the room is the scene's only light source, casting soft, direct light and shadows onto the others.)note")},
		{"A7", QObject::tr(R"note(Reuses the marble-textured ground from the marble-sphere scenes, but the real star here is light itself: a warm-glowing sphere and a cooler-toned glowing panel act as two very differently shaped light sources in the same room. Because one light is a curved ball and the other is a flat panel, this is a good place to see how light of different shapes and colors spreads and blends across nearby surfaces.)note")},
		{"A8", QObject::tr(R"note(Takes the familiar Cornell room and swaps out the two solid boxes for boxes filled with colored fog instead - so rather than blocking light like solid objects, they scatter it internally, giving them a soft, hazy, smoke-filled look rather than sharp edges. It's a good look at how the renderer handles fog and haze confined to a defined shape and thickness, rather than just flat, solid surfaces.)note")},
		{"A9", QObject::tr(R"note(The single busiest scene in the whole set, packing in nearly every trick at once: a rolling, uneven ground made from many small boxes of random heights, a glowing ceiling panel, a sphere that's visibly moving (motion blur), a glass sphere, a softly brushed-metal sphere, a glass sphere with colored fog trapped inside it like a snow globe, a very faint haze drifting through the whole room, a sphere textured with an image of Earth, a marble-patterned sphere, and a tight cluster of small white spheres in the corner. If a single render could show off everything this renderer can do, this would be it.)note")},

		// ---------------------------------------------------------------
		// Materials (B1-B14, B23) - procedural
		// ---------------------------------------------------------------
		{"B1", QObject::tr(R"note(Five gold-toned spheres sit in a row, each identical except for one thing: how rough its surface is. The leftmost is nearly mirror-smooth with a small, sharp reflected highlight; moving right, the surface gets progressively rougher and the highlight spreads into a soft, wide glow, the same way a brushed or satin-finished metal looks duller and blurrier than a polished one. It's a clean side-by-side look at how surface roughness alone changes a metal's appearance.)note")},
		{"B2", QObject::tr(R"note(The same brushed-metal look from the rough-metal row - a brushed aluminum box and a brushed gold sphere - but now placed inside the Cornell room, where it has to hold up under soft, colored, bounced light instead of one clean overhead studio light. Watch how the blurry, glossy reflections pick up hints of the room's colored walls.)note")},
		{"B3", QObject::tr(R"note(The usual clear glass sphere from the Cornell box is swapped for a frosted version - light passing through it scatters into a soft blur instead of bending sharply, the same way frosted or sandblasted glass looks compared to a clean windowpane. Reflections off its surface get the same soft, blurred treatment.)note")},
		{"B4", QObject::tr(R"note(Polished gold and aluminum surfaces get their color and shine from real measured optical data for each metal, rather than an artist just picking a gold or silver tint - so the color you see is physically how that metal actually reflects light, not an approximation.)note")},
		{"B5", QObject::tr(R"note(A sphere and a box look like they've been dipped in a clear varnish or lacquer: a glassy, reflective clear coat sits on top of an ordinary matte-colored surface underneath. Look closely at the highlights - some light bounces straight off the shiny outer coat, while the rest passes through and picks up the matte color beneath, with some light bouncing back and forth between the two layers before it escapes.)note")},
		{"B6", QObject::tr(R"note(A pane of glass divides the Cornell room in two, treated as an idealized zero-thickness sheet, so light passing through goes straight across without bending the way it would through a thick block of glass. It's tilted at an angle on purpose - glass barely reflects anything when you look straight through it, but becomes noticeably more mirror-like the more shallow the viewing angle gets, the same way a car windshield turns reflective at a glancing angle but seems to disappear when viewed head-on.)note")},
		{"B7", QObject::tr(R"note(A gold sphere and a copper box get a lacquered, showroom-finish look: a glassy clear coat sitting over the real metal's own reflective color underneath. It's the most layered material in this set, combining the metal's natural tinted shine with the coat's own separate highlight sitting on top of it.)note")},
		{"B8", QObject::tr(R"note(A sphere with a soft, wax-like, candle-lit quality: light doesn't just bounce off its surface, some of it also passes through and glows out the other side, scattered rather than sharp - a simple, inexpensive way to fake the look of translucent materials like wax or a lampshade, without simulating light actually bouncing around inside the object.)note")},
		{"B9", QObject::tr(R"note(A crystal-like sphere that glows more strongly near its edges than head-on - the same angle-dependent effect that makes a glass of water or a soap bubble look brighter and more reflective around its rim than through its center, applied here to how the material lets internally-scattered light escape.)note")},
		{"B10", QObject::tr(R"note(Seven spheres in a row demonstrate one flexible, do-it-all material sliding smoothly from plain matte, to glossy plastic, to plastic with a clear varnish-like coat, to semi-metallic, to rough brushed metal, and finally to a perfect, glass-smooth mirror finish (with and without a clear coat on top). Rather than needing a different material for each look, this one material can become almost any surface just by adjusting how metallic, how rough, and how glossy-coated it is.)note")},
		{"B11", QObject::tr(R"note(Five spheres are shaded with the same light-scattering model used for individual strands of hair - applied to spheres rather than actual hair-thin fibers, so you can study just the material's look in isolation (see the Curve Fibers scene for real hair-shaped geometry using the same idea). This material scatters light in a very strong, narrow, almost laser-like way, so much so that the light in this room had to be turned way down to avoid the highlights blowing out completely white.)note")},
		{"B12", QObject::tr(R"note(Two ways of faking fine surface detail without actually modeling it: the back wall and box appear to have a bumpy, marbled texture even though their underlying shape is completely flat, while the sphere appears to have a checkerboard pattern etched into its surface even though it's perfectly smooth. Both tricks work by subtly bending the direction light "thinks" the surface is facing, without changing the actual geometry at all.)note")},
		{"B13", QObject::tr(R"note(A milky wax slab and a jade sphere both have that soft, glowing-from-within look real translucent materials have - light enters through the glass-like outer surface, then scatters around and bounces inside the object for a while before finding its way back out, rather than just reflecting straight off the surface. It's the same look real subsurface materials like skin, milk, or jade are known for, achieved here by treating the inside of the object like a light-scattering fog rather than a specialized skin/translucency formula.)note")},
		{"B14", QObject::tr(R"note(Five spheres demonstrate support for real-world "measured" material data - the kind of tables you'd get from scanning an actual physical material sample in a lab, rather than describing a look with a handful of artist-friendly sliders. The data used here is synthetically generated rather than a real scan, and the shading itself is simplified, so this is really a check that the measured-data format loads and flows through correctly rather than a showcase of one specific real material.)note")},
		{"B23", QObject::tr(R"note(A glass prism, just like the ones used to demonstrate light and color in a science classroom: white light entering one face splits into a fan of rainbow colors as it exits, because glass bends different wavelengths of light by very slightly different amounts, matching how real glass behaves. That full rainbow spread only appears when the renderer is run in its special --spectral mode, which tracks individual wavelengths of light; otherwise, only a rough three-color (red/green/blue) approximation of the split shows up.)note")},
		{"B24", QObject::tr(R"note(The same rainbow-splitting glass prism as the smooth version, but ground to a frosted, sandblasted finish instead of polished. Run in --spectral mode, the same rainbow fan appears on the screen behind it, just blurred and softened by the frosted surface rather than sharply defined - proof that the color-splitting effect and the frosted-glass blur are two independent things happening together correctly, rather than the rough surface accidentally washing out the colors.)note")},

		// ---------------------------------------------------------------
		// Materials (B15-B16, B18, B20, B22, B25) - curated pbrt examples
		// ---------------------------------------------------------------
		{"B15", QObject::tr(R"note(Blends a plain matte material and a shiny metallic one at every point on the surface - not by mixing their colors into some in-between shade, but by randomly picking one or the other for each individual light sample. Look closely and the result has a genuine speckled, grainy quality, with some spots behaving purely matte and others purely shiny, which only averages out into a smooth in-between look once enough samples pile up.)note")},
		{"B16", QObject::tr(R"note(Four distinct material looks side by side: an idealized paper-thin glass sheet that bends light without displacing it sideways, a metal with a clear lacquer coat over it, a material like a thin leaf or piece of paper that both reflects and lets light through, and a block using a built-in "Marble" preset for the soft glow of subsurface scattering without needing any external scanned data.)note")},
		{"B18", QObject::tr(R"note(A metal surface, and a lacquer-coated version of the same metal, get their color and reflectivity from raw physical light-bending numbers entered directly, rather than picking a preset named metal - producing an accurate, naturally tinted specular highlight instead of a flat, artist-chosen metallic color.)note")},
		{"B20", QObject::tr(R"note(Uses the same physically-based hair-shading model real film production renderers use for photorealistic hair and fur, applied here to plain spheres for a clean, controlled comparison against this project's own separate hair-strand demo scene.)note")},
		{"B22", QObject::tr(R"note(A single material is defined once and then reused by name across multiple objects, with one of its properties driven by an image texture rather than a flat color - and the scene's light source is set to shine from both of its faces rather than just one side, like a light panel someone remembered has a front and a back.)note")},
		{"B25", QObject::tr(R"note(Seven glass spheres, each using a different named real-world optical glass type (the same names found in actual camera-lens catalogs), each bending light by a very slightly different amount. It's a look at how a lens designer's choice of glass translates into small but real differences in how a material bends light.)note")},

		// ---------------------------------------------------------------
		// Textures (J1-J6) - curated pbrt examples, split out of Materials
		// ---------------------------------------------------------------
		{"J1", QObject::tr(R"note(A varnished-wood-like material - a matte base color under a clear glossy coat - gets its base color from an actual photograph mapped onto the surface instead of a single flat color. This exact pairing once had a bug where the image was silently ignored in favor of plain grey, so this scene exists to prove the image now shows up correctly.)note")},
		{"J2", QObject::tr(R"note(A material like a thin leaf or lampshade - one that both reflects light off its front and lets light glow through from behind - has both its reflected and transmitted colors driven by real photographs instead of flat colors, checked on every supported way of rendering it.)note")},
		{"J3", QObject::tr(R"note(A checkerboard pattern where each of its two "colors" is actually a whole separate photograph rather than a flat color swatch - a texture nested inside another texture, showing that textures can be layered and combined, not just used one at a time.)note")},
		{"J4", QObject::tr(R"note(Four identical panels, same source photo, each demonstrating a different way an image can be decoded and applied: the standard look most images use, a noticeably brighter version that skips a color-correction step most cameras and screens expect, a version that holds onto its edge pixel instead of repeating the pattern when stretched past its border, and a version with its color channels flipped. Side by side, they make some usually-invisible image-handling settings easy to actually see.)note")},
		{"J5", QObject::tr(R"note(Four panels, each showing off a different procedural pattern generated purely by a formula rather than a photograph: a windswept, turbulent look; a wrinkled, cloud-like surface with adjustable fine detail; a two-color pattern split along a naturally wavy, noise-drawn boundary; and a smooth blend between four different corner colors.)note")},
		{"J6", QObject::tr(R"note(Compares a checkerboard-inside-a-checkerboard-inside-a-photograph - three layers of pattern nested inside each other - against the simpler single-layer version placed right next to it. Rendered on the CPU, the full nested detail shows through correctly; rendered on the GPU, it's intentionally simplified down to one averaged color instead (with a warning), a known, accepted shortcut rather than a bug - so this scene is a deliberate side-by-side of that difference.)note")},

		// ---------------------------------------------------------------
		// Lights (C1-C7) - procedural
		// ---------------------------------------------------------------
		{"C1", QObject::tr(R"note(An open scene lit only by a sky - a smooth gradient from blue overhead to a warm glow near the horizon, standing in for a whole environment rather than a single light bulb or panel. A plain matte sphere, a near-perfect mirror, and a glass sphere sit underneath it, showing how the exact same sky reads completely differently depending on the material: soft and shadow-like on the matte sphere, a sharp reflected copy of the sky on the mirror, and a bent, refracted view of it through the glass.)note")},
		{"C2", QObject::tr(R"note(An empty room lit by a single spotlight aimed straight down from the ceiling, with soft, gradually-fading edges rather than a hard-edged circle of light - the way a well-designed stage or track spotlight looks, rather than a harsh flashlight beam.)note")},
		{"C3", QObject::tr(R"note(An empty room lit like it's sitting outdoors under direct sunlight: the light comes from one fixed direction with perfectly parallel rays, and unlike a lamp or bulb, it doesn't get dimmer with distance - the light would stay just as bright no matter how far apart the walls were moved.)note")},
		{"C4", QObject::tr(R"note(An empty room lit by the simplest kind of light there is: a single point in space glowing equally in every direction, getting dimmer the farther away a surface is from it, similar to how the light from a small bare bulb rapidly fades with distance.)note")},
		{"C5", QObject::tr(R"note(An empty room lit by a light with an uneven, custom-shaped glow - brighter in some directions than others, following an actual measured pattern rather than shining the same in every direction, similar to how a real desk lamp or fixture often throws more light one way than another depending on its shade or reflector.)note")},
		{"C6", QObject::tr(R"note(An empty room lit by a light that projects a patterned image, like an old-fashioned slide projector, casting a sharp checkerboard beam onto the walls instead of a plain, evenly-lit cone or sphere of light.)note")},
		{"C7", QObject::tr(R"note(A Cornell-style room with no ceiling light at all - instead, there's an actual window-shaped hole cut into the back wall, and all the light comes from a sky glimpsed through that opening. It's a much harder lighting puzzle than a light panel sitting right in the room, since the renderer has to figure out how to aim rays through a narrow window toward a sky that's everywhere outside it, rather than toward a nearby light it can point straight at.)note")},

		// ---------------------------------------------------------------
		// Lights (C8-C20) - curated pbrt examples
		// ---------------------------------------------------------------
		{"C8", QObject::tr(R"note(All five basic "single point" light types side by side in one room - a plain point light, a spotlight, a distant sun-like light, a light with a custom directional glow pattern, and a slide-projector-style light - a handy lineup for comparing every simple, sizeless light source at a glance.)note")},
		{"C9", QObject::tr(R"note(Checks that two of the light types that are supposed to project a real image - a light with a custom directional-glow pattern and a slide-projector-style light - actually read and display their assigned images now, rather than silently falling back to a plain, featureless beam like they once did.)note")},
		{"C10", QObject::tr(R"note(Two glowing panels lit at different temperatures, measured in Kelvin the same way you'd describe a photo studio light bulb or a camera's color-temperature setting: one panel glows a warm, cozy, incandescent-bulb orange, the other a cool, overcast, cloudy-sky blue-white. If the underlying color math ever broke, both panels would flatten out to the same plain white, so keeping them visibly different is the whole point.)note")},
		{"C11", QObject::tr(R"note(A glowing shape (a sphere or a panel) that gets its glow pattern from an actual image rather than shining a single flat color, and shines that pattern from both of its faces rather than just the one side it normally points toward.)note")},
		{"C12", QObject::tr(R"note(The simplest possible stand-in for a sky: a flat, constant color glowing in from every direction at once, with no visible shape of its own. It only does anything useful in an open scene - inside a fully closed room it would be blocked out entirely, the same way you can't see the sky from inside a sealed box.)note")},
		{"C13", QObject::tr(R"note(A disk-shaped and a cylinder-shaped light, each treated as a real light source that the renderer deliberately aims sample rays toward rather than hoping a ray randomly bounces into it. That deliberate aiming is what makes a scene converge to a clean, smooth-looking image quickly rather than staying speckled and noisy for a long time.)note")},
		{"C14", QObject::tr(R"note(Two separate glowing spheres light this simple room - a minimal setup that once exposed a real bug where the renderer's GPU code only kept track of one light's type properly, so any additional light after the first was misidentified and rendered incorrectly.)note")},
		{"C15", QObject::tr(R"note(A light shaped like an irregular, five-sided fan rather than a simple flat rectangle - awkward enough in shape that the renderer can't take its usual shortcut of treating pairs of triangles as one simplified rectangle for sampling, forcing it to handle the oddly-shaped light for real.)note")},
		{"C16", QObject::tr(R"note(Identical geometry and identical warm/cool light temperatures to the Blackbody Light scene, but rendered using a wider, more film-camera-like color space instead of the everyday one most screens use. Comparing the two scenes side by side is a direct, visible proof that choosing a different color space actually changes the final colors, rather than being a setting that's silently ignored.)note")},
		{"C17", QObject::tr(R"note(A Cornell-style room with a window cut into the back wall, showing a genuine high-resolution sky photo through that opening rather than a flat glow. Unlike the simpler portal-light scene elsewhere in this gallery, the view through the window here is real sky detail, not just a plain colored light peeking through a hole.)note")},
		{"C18", QObject::tr(R"note(Three identical spheres, each lit by a different kind of light - a bare point light, a spotlight, and a glowing panel - but each one's brightness is set as total light output, like the wattage printed on a lightbulb box, rather than a raw brightness number. Converting that fairly into an actual visible glow works differently for each light shape, so if any one of the three spheres came out too bright or too dim compared to the others, it would stand out immediately.)note")},
		{"C19", QObject::tr(R"note(A slide-projector light throws a wide, non-square image - twice as wide as it is tall - onto the scene, instead of the usual square test pattern other projector-light scenes use. Done correctly, the projected patch should be noticeably rectangular, matching the slide's own proportions; a bug here would show up as the patch getting squished square or stretched to fill the beam instead.)note")},
		{"C20", QObject::tr(R"note(Three richly colored lights - red, green, and blue - overlap on a plain surface at close range, right where the mixed colors push the edge of what a normal screen can display. Where they blend, you should see a smooth, natural transition toward white and pastel tones; a rendering bug here used to show up as muddy, darkened patches or visible banding right where the colors mixed together.)note")},

		// ---------------------------------------------------------------
		// Cameras (D1-D8) - procedural
		// ---------------------------------------------------------------
		{"D1", QObject::tr(R"note(A checkerboard floor with a scattering of glass and metal spheres at different distances, rendered with realistic camera focus. Only the sphere sitting exactly at the focus distance is razor-sharp, while everything nearer or farther fades into a soft blur - just like looking through a real camera lens.)note")},
		{"D2", QObject::tr(R"note(A row of spheres over a checkered floor, viewed through a camera with no perspective at all - rays travel perfectly parallel instead of converging toward a single eye point, so every sphere reads as the same size on screen no matter how far away it actually is. That's the classic giveaway of an architectural-style flat view, quite different from how an ordinary photo looks.)note")},
		{"D3", QObject::tr(R"note(A ring of colored spheres surrounding a single glowing sphere at the center, captured with a 360-degree panoramic camera - the entire surrounding view, in every direction at once, gets flattened into one wraparound image instead of the usual boxed-in photo frame.)note")},
		{"D4", QObject::tr(R"note(Five spheres marching off into the distance over a checkered floor, shot through a simulated real camera lens - built from actual glass elements with their own curvature and thickness - rather than a simplified mathematical stand-in. The out-of-focus blur and the slight darkening toward the frame's edges are genuine side effects of light bending through a real lens stack, not a shortcut effect.)note")},
		{"D5", QObject::tr(R"note(The same Cornell box used throughout this camera-comparison set, this time shown with soft, photographic depth-of-field blur - handy for seeing exactly what that effect looks like on a room you can also view through the other camera types nearby, with nothing else about the scene changed.)note")},
		{"D6", QObject::tr(R"note(The same shared Cornell box, viewed straight down its length through a parallel-projection camera. Because there's no perspective convergence, the box's edges stay perfectly parallel all the way to the frame's border, instead of narrowing toward a vanishing point the way an ordinary camera view would.)note")},
		{"D7", QObject::tr(R"note(The same shared Cornell box, this time toured with a 360-degree panoramic camera placed right at its center - the ceiling light, all five walls, and the glass sphere all wrap into one continuous image, as though you were standing in the middle of the room looking every direction at once.)note")},
		{"D8", QObject::tr(R"note(The same shared Cornell box, shot through the same simulated real-lens camera as the standalone lens-demo scene, with its aperture opened up to match the room's larger size - so the blurry, out-of-focus look reads at a similar visual strength despite the bigger scale.)note")},
		{"D13", QObject::tr(R"note(The same shared Cornell box, but this time the camera itself glides from one side to the other while the shutter is open, producing real motion blur rather than a frozen frame. This only shows up when rendering with the standard path tracer or the photon-based SPPM mode - other rendering modes, and the GPU, just show the camera parked at its starting position instead.)note")},

		// ---------------------------------------------------------------
		// Cameras (D9-D12) - curated pbrt examples
		// ---------------------------------------------------------------
		{"D9", QObject::tr(R"note(A camera's realistic focus blur - aperture size and focus distance - loaded from an external scene description file rather than built into the program. The same optical effect as this project's own native depth-of-field scene, just arriving through file loading instead.)note")},
		{"D10", QObject::tr(R"note(A parallel-projection camera loaded from a scene file - rays travel perfectly parallel instead of converging toward a viewpoint, so two identical spheres at different distances appear the same size on screen instead of the nearer one looking bigger, the opposite of how an ordinary photo behaves.)note")},
		{"D11", QObject::tr(R"note(A 360-degree panoramic camera loaded from a scene file - rays fan out in every direction from a single point rather than through a normal flat picture frame, letting one image capture an entire surrounding view. Placed inside an enclosed room so there's always something to see in every direction.)note")},
		{"D12", QObject::tr(R"note(A genuine multi-element camera lens - not the simplified idealized lens every other camera scene uses - loaded from an external lens-design file and traced ray by ray through its actual glass elements, producing authentic depth-of-field blur and lens imperfections.)note")},

		// ---------------------------------------------------------------
		// Volumes (E1-E4) - procedural
		// ---------------------------------------------------------------
		{"E1", QObject::tr(R"note(A Cornell box filled edge-to-edge with an even, uniform fog - every point inside has exactly the same thickness and scattering behavior, giving the simplest, most even kind of hazy look that light picks up scattering through a room.)note")},
		{"E2", QObject::tr(R"note(A realistic-looking cloud whose wispy shape comes from layered, naturally-varied Perlin noise rather than a fixed uniform block of fog - denser near the base and thinning out toward the top, the way a real cloud does. Rendering fog whose thickness varies from point to point like this needs a technique built specifically for handling that varying density realistically, which is exactly what this scene tests.)note")},
		{"E3", QObject::tr(R"note(Glass spheres, each filled with an internal fog of a different density. Light has to bend as it enters through the glass surface, scatter or get absorbed by the fog inside, then bend again on its way back out - rather than simply bouncing off an opaque shell.)note")},
		{"E4", QObject::tr(R"note(A cloud-like volume built from real per-cell density data on a 3D grid, with red, green, and blue given independently varying patterns so the color drifts and shifts through the cloud instead of reading as one flat, uniform tint.)note")},

		// ---------------------------------------------------------------
		// Volumes (E5-E10) - curated pbrt examples
		// ---------------------------------------------------------------
		{"E5", QObject::tr(R"note(A cloud loaded from an external scene file, its shape driven by the same kind of naturally-varied noise pattern real cloud rendering uses to avoid looking like a flat, obviously fake block of fog.)note")},
		{"E6", QObject::tr(R"note(A simple, uniform fog wrapped around a cylinder shape - this exact pairing used to silently render as a plain, fog-free cylinder on the GPU, so this scene exists to make sure the haze actually shows up there too.)note")},
		{"E7", QObject::tr(R"note(A voxel-based volume where each little cell carries its own color, not just a density value - rendering as a soft, colorful, nebula-like cloud rather than a single uniformly tinted fog.)note")},
		{"E8", QObject::tr(R"note(A voxel-based volume with just a single density value per cell and no per-cell color - rendering as a simpler, softly glowing fog blob, the plainer sibling of the colorful grid-cloud scene.)note")},
		{"E9", QObject::tr(R"note(A real sparse cloud-data file, the same format used by professional visual-effects software, loaded in and rendered as a soft fog sphere. Sparse data like this needs a very different lookup approach than an ordinary evenly-spaced grid, making it one of the trickier formats to support well. Works fully on the CPU; on the GPU it currently falls back to a plain, evenly-thick fog instead, as a known simplification rather than a bug.)note")},
		{"E10", QObject::tr(R"note(The camera itself sits inside a haze with no surrounding shape at all, as if the lens were fogged over - a genuinely different setup from every other fog scene here, which all put the viewer looking at a foggy object from the outside. Works on the CPU and one of the two GPU rendering paths; the other GPU path doesn't support it yet and just renders without any fog at all.)note")},

		// ---------------------------------------------------------------
		// Geometry (F1, F2, F4) - procedural
		// ---------------------------------------------------------------
		{"F1", QObject::tr(R"note(Two curved surfaces - a saddle shape and a smooth ramp - built directly from just their four corner points rather than approximated with flat triangles. A softly blurred metal finish is used deliberately, so the shading gradient reveals the surface's true curve; a perfect mirror finish would just show one sharp highlight and hide the fact that the surface isn't flat at all.)note")},
		{"F2", QObject::tr(R"note(A hand-built 20-sided die shape (an icosahedron), assembled as a real triangle mesh. Each flat triangular face shows its own distinct shading rather than blending smoothly into its neighbors, giving it a faceted, low-poly look instead of a smooth, rounded one.)note")},
		{"F4", QObject::tr(R"note(Real curved, tapering strands - thick at the root and thinning toward the tip - scattered across a surface, built from genuinely curved geometry rather than the flat "sphere shaded to look like hair" trick used in the separate Hair Fibers scene.)note")},

		// ---------------------------------------------------------------
		// Geometry (F5-F14) - curated pbrt examples
		// ---------------------------------------------------------------
		{"F5", QObject::tr(R"note(An externally loaded 3D model with real texture-coordinate data baked in, so an image can wrap correctly around its surface. This exact scene used to render solid black on one of the GPU rendering paths, because that texture data was being silently dropped.)note")},
		{"F6", QObject::tr(R"note(A real external 3D model file loaded start to finish, including a face in the original file that wasn't already made of triangles - the loader has to split it into triangles itself rather than assuming the file already did that work.)note")},
		{"F7", QObject::tr(R"note(True curved fiber strands, smoothly rounded rather than built from flat triangles, shown side by side with this project's own native hair-strand demo built the same way - a direct comparison of the two approaches to the same visual effect.)note")},
		{"F8", QObject::tr(R"note(Real curved fiber strands paired with a proper hair-like material for the first time - together, they exposed a bug where the shine along each strand was computed as if the strand were a flat surface instead of a curved fiber, which is exactly what gives a strand of hair its characteristic streak of highlight running along its length rather than a dull, matte look.)note")},
		{"F9", QObject::tr(R"note(A triangle-based 3D shape with explicit texture coordinates set on each corner, so images can be applied to it correctly. One of the two GPU rendering paths used to render this exact scene solid black before that texture-coordinate support existed.)note")},
		{"F10", QObject::tr(R"note(This scene deliberately uses a simpler, blockier way of turning many samples into a final pixel color, giving edges and silhouettes a slightly harder, more jagged look than the smoother default. Compare it against any other scene's usual soft-edged rendering to see the difference.)note")},
		{"F11", QObject::tr(R"note(A single sphere is given two different positions at the start and end of the simulated camera shutter, so it should render as a soft directional streak between the two - true motion blur - rather than a sharp still sphere or an oddly doubled copy. A stationary reference sphere sits alongside it for comparison. This works correctly on every rendering backend the project supports.)note")},
		{"F12", QObject::tr(R"note(The same start-and-end-position motion-blur trick as the sphere motion-blur scene, but applied to a disk and a cylinder instead - shapes that store their movement a bit differently under the hood. This one only works when rendering on the CPU; both GPU rendering paths currently just show these shapes frozen in their starting pose instead of blurred.)note")},
		{"F13", QObject::tr(R"note(Two identical flat panels are built from the exact same geometry, which by default would make both of them face away from the camera and stay dark as light sources. Flipping just the second one's facing direction makes it light up while the first stays dark - a clean visual check that a shape's facing direction is being respected correctly, since a mistake here would show either both panels dark or both lit.)note")},
		{"F14", QObject::tr(R"note(Four shapes built from an older cone- and dish-shaped (paraboloid) primitive kept around for compatibility with older scene files: a plain cone, a plain dish shape, a cone used as a glowing light source instead of an ordinary surface, and a dish shape used as a fog boundary with its open end facing the camera, so rays can drift into the fog through the opening rather than punching through solid material. Only rendered on the CPU - both GPU paths skip cone and dish shapes entirely.)note")},

		// ---------------------------------------------------------------
		// Models (G25) - curated pbrt example
		// ---------------------------------------------------------------
		{"G25", QObject::tr(R"note(A classic, detailed statue model, arriving as a complete self-contained scene file - geometry, materials, lighting, and camera all defined in the file itself - exactly the same loading path a user's own custom scene files would go through.)note")},

		// ---------------------------------------------------------------
		// Education (I1-I10) - Render Options tab demos
		// ---------------------------------------------------------------
		{"I1", QObject::tr(R"note(The same Cornell box as the very first demo scene, deliberately rendered with far fewer samples than usual so it stays noticeably grainy instead of converging cleanly. Try switching the Sampler option on the Render Options tab through its different choices (Sobol, Z-Sobol, Padded Sobol, Stratified, PMJ02BN, Halton) and re-render - each one spreads those samples across the pixel and toward the light in a different pattern, so the graininess along the soft shadow's edge looks a little different for each, even though nothing else about the scene changes. This only affects the CPU's default renderer - the Sampler option has no effect when rendering on the GPU.)note")},
		{"I2", QObject::tr(R"note(The same glass prism as the Spectral Dispersion scene, built specifically to show off the Spectral rendering checkbox on the Render Options tab. With it off, the renderer only tracks red, green, and blue, so every color of light bends by the same amount passing through the glass. Switched on, the renderer tracks individual wavelengths of light, so the glass bends each one very slightly differently - fanning white light out into a visible rainbow, the same way a real glass prism does. CPU only.)note")},
		{"I3", QObject::tr(R"note(The same bright sky-and-shadow scene as the HDRI Sky demo, whose true brightness spans a much wider range than any screen can show at once. Two Render Options tab controls handle that range differently: Exposure is a simple brightness multiplier applied first, evenly brightening everything, sky and sphere alike. Tone mapping is a curve applied afterward that squeezes that wide range down into something a screen can display - ACES gently rolls off the brightest parts of the sky, Reinhard compresses more aggressively, and None just clips the brightest areas to flat white. Try a few different Tone mapping choices at a couple of different Exposure levels to see how the two controls act independently. Works on both CPU and GPU.)note")},
		{"I4", QObject::tr(R"note(The same first Cornell box demo, rendered with a very low number of samples so it looks genuinely grainy - render it once with the OptiX AI denoiser (Render Options tab) turned off, then once with it on. The denoiser is a machine-learning model that recognizes that speckled noise pattern and smooths it away without tracing a single extra ray, trading a small amount of fine detail for a much cleaner-looking image at no extra rendering cost. Requires the OptiX GPU backend (Windows) - it has no Metal equivalent, so this demo isn't available on macOS. The nearby OptiX validation mode checkbox is worth knowing about too, but it's different - it only turns on extra internal safety checks with a performance cost, and never changes what the image looks like, so there's nothing to visually compare there.)note")},
		{"I5", QObject::tr(R"note(The same frosted-glass Cornell box as the Cornell Rough Glass scene, built to show off the SPPM option in the Integrator dropdown. Render it once with the default Path Tracer and once with SPPM (Render Options tab) at the same sample count - the bright, focused patch of light under the rough glass sphere (a caustic) is exactly the kind of tricky lighting that ordinary path tracing struggles to clean up quickly. SPPM traces light from the light source first, records where it lands, then gathers that up from the camera's side - an approach built specifically for lighting like this, so the caustic should visibly sharpen up much faster.)note")},
		{"I6", QObject::tr(R"note(The same first Cornell box demo, built to show off the Integrator dropdown's BDPT and MLT options. Try either one (Render Options tab) instead of the default Path Tracer: both trace light paths starting from the camera and from the light source at the same time, then connect them partway - a fundamentally different strategy from the default renderer or SPPM, which only trace from the camera. On a scene like this, with meaningful bounced lighting, that different strategy can converge differently, sometimes better, sometimes just with a different noise character.)note")},
		{"I7", QObject::tr(R"note(The same first Cornell box demo, used as a tour through the Integrator dropdown's reference and debug modes. RandomWalk just bounces each ray off in a random direction with no attempt to aim at the lights and no smart blending of strategies - the simplest, slowest-converging, but most "honest" baseline. SimplePath adds two independent checkboxes for exactly those two ingredients: with only "sample lights" on, direct lighting comes in cheaply, but a bounce that happens to point toward a bright light off to the side is just luck; with only "sample BSDF" on, it's the other way around; with both on, the two strategies get combined for a cleaner result - which is also what the default Path Tracer already does behind the scenes. Render each at the same low sample count to see how differently they converge on the exact same room.)note")},
		{"I8", QObject::tr(R"note(A Cornell box built specifically for this demo, with five ceiling lights instead of the usual one, and deliberately very uneven brightness between them (roughly 1:2:6:15:80). The Uniform light sampler (Render Options tab) spends an equal fifth of its light-aiming effort on each of the five lights regardless of how much each one actually matters - so it wastes most of its effort on four lights that barely contribute, leaving the one genuinely bright light noisier than it needs to be. Power and BVH both instead weight their effort toward that dominant light (BVH also factors in distance and direction, Power only in total brightness) - render all three at the same low sample count and compare how much faster the noise around the bright corner light settles down.)note")},
		{"I9", QObject::tr(R"note(The same first Cornell box demo, used to show off the Integrator dropdown's Ambient Occlusion mode. AO isn't a normal lit render at all - switch to it (Render Options tab) and every surface's actual color and every real light in the scene get ignored completely, replaced with a simple grayscale measure of how enclosed each point is by nearby geometry. All that's left is the box's own contact shadows and the corners where walls meet, which is exactly what makes AO a fast way to preview a scene's shape and geometric complexity without worrying about its lighting at all.)note")},
		{"I10", QObject::tr(R"note(The same frosted-glass Cornell box as the Cornell Rough Glass and SPPM demo scenes - the bright focused patch of light under the rough glass sphere is a classic source of stray, isolated overly-bright pixels ("fireflies") under ordinary path tracing. Regularize and Firefly clamp (both on the Render Options tab) fix that two different ways: Regularize gently blurs the glass's own roughness after the first bounce, making that tricky lighting easier to sample cleanly in the first place; the Firefly clamp instead lets the bright pixel happen, then caps how bright any single sample is allowed to get, trading a tiny bit of accuracy for a guaranteed ceiling on stray bright spots. Render the scene plain, then with each option on its own, at the same sample count, to compare.)note")},
	};
	return kNotes;
}

// Returns the technique note for `sceneId`, or an honest fallback: an
// empty/unrecognized id (no scene selected, or the search box narrowed to
// zero matches) gets a neutral prompt; a real scene id with no authored
// entry - every scene outside the self-contained set - gets a message
// explaining why, rather than silently showing nothing or stale text.
// Whether an authored note exists for `sceneId`, distinct from forScene()
// having *some* text to return - forScene()'s own fallback text for a
// not-yet-authored scene is written for the Settings tab ("the tab
// above"), so callers elsewhere (e.g. the Preview tab) that want to hide
// rather than show that fallback should gate on this first.
inline bool hasNote(const QString &sceneId) {
	return notes().contains(sceneId);
}

inline QString forScene(const QString &sceneId) {
	if (sceneId.isEmpty())
		return QObject::tr("Select a scene to see the rendering technique it demonstrates.");
	const auto &map = notes();
	const auto it = map.constFind(sceneId);
	if (it != map.constEnd())
		return it.value();
	return QObject::tr(
		"No rendering-technique note is written for this scene yet - these are "
		"only authored for the self-contained scene set (the \"Self-Contained\" "
		"tab above) so far.");
}

// Debug-only drift guard, called once from createSettingsTab() (mainwindow_tabs.cpp)
// after it enumerates the live scene list. scene_registry.h already lost one
// GUI-facing mirror table to exactly this failure mode once (see that file's
// own comment on scene_descriptor.h's old kScenes[]) and this table is the
// same shape of duplicate for a different field, so it gets the same kind of
// tripwire scene_registry_tests.cpp's GuiSceneCountMatchesRegistry test is
// for the scene count - just as a runtime qWarning() rather than a gtest
// assertion, because this header depends on Qt and the core test binary is
// deliberately Qt-free (see ray_tracer_tests.vcxproj's own comment on
// palette_file.h) so it can't link scene_registry.h itself to compare against
// (scene_metadata_client.h's comment: the GUI never links that header
// directly, only through the DLL boundary this function's caller already
// uses). Fails loud via qWarning, not a crash or a dialog - same "say so,
// don't stay silent" choice ThemedScrollArea::setMotif()'s missing-resource
// warning (mainwindow.h) makes elsewhere in this app.
inline void warnIfOutOfSync(const QStringList &selfContainedSceneIds) {
	const auto &map = notes();
	for (const QString &id : selfContainedSceneIds) {
		if (!map.contains(id)) {
			qWarning() << "scene_technique_notes.h: self-contained scene" << id
					   << "has no authored technique note - its info icon will show the generic fallback.";
		}
	}
	const QSet<QString> selfContainedSet(selfContainedSceneIds.constBegin(), selfContainedSceneIds.constEnd());
	for (auto it = map.constBegin(); it != map.constEnd(); ++it) {
		if (!selfContainedSet.contains(it.key())) {
			qWarning() << "scene_technique_notes.h: entry" << it.key()
					   << "does not match any current self-contained scene - stale, renamed, or moved to \"Requires External Files\"?";
		}
	}
}

} // namespace scene_technique_notes
